### ISSUE TITLE
Using the old flexDrive 64-channel EIB

### ISSUE THREAD

**Issue by teristam** [open-ephys/shuttle-drive#1]
Hi,

Our lab has a bunch of 64-channel EIB for flexDrive lying around but we would like to try the new shuttle drive. May I ask if the old EIBs are still usable with the new shuttle drive?

Thanks!

**Comment by jvoigts** [comment]
Hi,
no the old EIBs will not fit the new drives. They are both too large, and the gold pins are too far out on the periphery of the pcb. If you want to recover the omnetics connectors you can hold the old eib by the connector with forceps and heat the pcb from below with a hot air soldering tool until it falls down. Re-soldering them onto the new eib pcbs however is a bit tricky due to the close spacing.
